package db

const SchemaComments = `
	CREATE TABLE IF NOT EXISTS comments (
		ID SERIAL PRIMARY KEY,
		ThreadID INT NOT NULL,
		UserID INT NOT NULL,
		Content VARCHAR(1000) NOT NULL,
		CreatedAT TIMESTAMPTZ NOT NULL DEFAULT NOW()
	);

	CREATE TABLE IF NOT EXISTS likes (
		ID SERIAL PRIMARY KEY,
		CommentID INT NOT NULL,
		UserID INT NOT NULL
	);
`
